site_name: the unprofessional node
site_url: https://t4gamer.github.io/
nav:
  - Home: index.md
  - Git good: git.md
theme:
  name: material
  features:
    - content.code.copy
    - content.code.annotate # (1)

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - md_in_html

extra:
  annotate:
    json: [.s2]