site_name: the unprofessional node
site_url: https://t4gamer.github.io/
nav:
  - Home: index.md
  - Git good: git.md
  - Html: html.md
theme:
  name: material
  features:
    - content.code.copy
    - content.code.annotate # (1)

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - md_in_html
  - attr_list
  - def_list
  - admonition
  - pymdownx.details # Required for collapsible admonitions
  - pymdownx.superfences
plugins:
  - search
  - macros

extra:
  annotate:
    json: [.s2]
extra_css:
  - snippets/position.css
